# Generated by Django 3.0.6 on 2020-11-22 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daemon_loops', '0003_sentplannedmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentplannedmessage',
            old_name='sender_id',
            new_name='receiver_id',
        ),
    ]
