# Generated by Django 3.0.6 on 2020-11-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('daemon_loops', '0007_senttweeturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedtweet',
            name='sender_name',
            field=models.CharField(default='[une certaine personne]', max_length=100),
            preserve_default=False,
        ),
    ]
