# Generated by Django 3.0.6 on 2020-11-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('daemon_loops', '0008_postedtweet_sender_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentTextSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campain_id', models.CharField(max_length=50)),
                ('text_id', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField()),
                ('receiver_id', models.CharField(max_length=50)),
                ('sent_text', models.TextField()),
            ],
        ),
    ]
