# Generated by Django 3.0.6 on 2020-11-25 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daemon_loops', '0009_senttextsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigParticicipantlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campain_id', models.CharField(max_length=50)),
                ('participant_id', models.CharField(max_length=50)),
                ('display_name_for_animators', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campain_id', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=300)),
                ('value_str', models.TextField(null=True)),
                ('value_float', models.FloatField(null=True)),
                ('value_bool', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigAdmins',
            fields=[
                ('configparticicipantlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='daemon_loops.ConfigParticicipantlist')),
            ],
            bases=('daemon_loops.configparticicipantlist',),
        ),
        migrations.CreateModel(
            name='ConfigReachableParticipants',
            fields=[
                ('configparticicipantlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='daemon_loops.ConfigParticicipantlist')),
            ],
            bases=('daemon_loops.configparticicipantlist',),
        ),
        migrations.CreateModel(
            name='ConfigRobotScribes',
            fields=[
                ('configparticicipantlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='daemon_loops.ConfigParticicipantlist')),
            ],
            bases=('daemon_loops.configparticicipantlist',),
        ),
        migrations.CreateModel(
            name='ConfigScribes',
            fields=[
                ('configparticicipantlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='daemon_loops.ConfigParticicipantlist')),
            ],
            bases=('daemon_loops.configparticicipantlist',),
        ),
    ]
